import test from 'node:test';
import assert from 'node:assert/strict';
import {OfflineAudioContext} from 'node-web-audio-api';
import {ProceduralCharacter} from '../src/audio/ProceduralCharacter.js';
import {SignalGraph,validateGraph} from '../src/audio/SignalGraph.js';
const rms=data=>Math.sqrt(data.reduce((sum,v)=>sum+v*v,0)/data.length);
async function character(params,cue){const ctx=new OfflineAudioContext(1,44100*3,44100),fx=new ProceduralCharacter(ctx,ctx.destination);fx.configure({lifecycleSounds:0,tieSignature:0,digitalCueLevel:0,...params});fx.start();fx.update({rpmNorm:.65,throttle:.7});if(cue)fx.cue(cue);const b=await ctx.startRendering();for(const v of b.getChannelData(0))assert.ok(Number.isFinite(v)&&Math.abs(v)<1.1);fx.dispose();assert.equal(fx.nodes.length,0);assert.equal(fx.sources.length,0);assert.equal(fx.shots.size,0);return rms(b.getChannelData(0));}
test('optional character layers are silent when disabled and audible independently',async()=>{assert.equal(await character({}),0);for(const params of [{tieSignature:1},{interiorNoise:1},{targetingNoise:1},{digitalCueLevel:.4}])assert.ok(await character(params)>.0001);});
test('lifecycle, gearing and blasters produce finite original procedural cues',async()=>{for(const cue of ['startup','shutdown','gearing','blaster'])assert.ok(await character({},cue)>.0001);});
test('roar variants and pitch controls change the rendered signal',async()=>{const values=[];for(let roarVariant=0;roarVariant<3;roarVariant++)values.push(await character({tieSignature:1,roarVariant,roarPitch:.6+roarVariant*.4}));assert.ok(Math.max(...values)-Math.min(...values)>.001);});
async function graphRender(frequency,connected=true,gain=1){const ctx=new OfflineAudioContext(1,22050,44100),input=ctx.createGain(),graph=new SignalGraph(ctx,input,ctx.destination);graph.configure([{id:'s',type:'Osc',params:{frequency:2000,gain:.4},outs:connected?[{to:'f'}]:[]},{id:'f',type:'Filter',params:{frequency,Q:.7},outs:[{to:'o'}]},{id:'o',type:'Output',params:{gain},outs:[]}]);graph.start();const b=await ctx.startRendering();graph.dispose();assert.equal(graph.nodes.size,0);return rms(b.getChannelData(0).slice(4410));}
test('real graph connections, filter cutoff and output gain affect audio',async()=>{const open=await graphRender(12000),closed=await graphRender(100);assert.ok(open>closed*10);assert.equal(await graphRender(12000,false),0);assert.ok(await graphRender(12000,true,.2)<open*.3);});
test('invalid connections and cycles are rejected before graph mutation',()=>{assert.throws(()=>validateGraph([{id:'a',outs:[{to:'missing'}]}]),/destination/);assert.throws(()=>validateGraph([{id:'a',outs:[{to:'b'}]},{id:'b',outs:[{to:'a'}]}]),/Feedback/);});
test('all three roar layers can stack without clipping and new cues are audible',async()=>{assert.ok(await character({tieSignature:1,roarOne:1,roarTwo:1,roarThree:1,roarDepth:1,roarAir:1,roarWidth:1})>.001);for(const cue of ['ion-cannon','lock','time-jump'])assert.ok(await character({},cue)>.0001);});
